### ISSUE TITLE
Update prodidows 1.50

### ISSUE THREAD

**Issue by Toonigy** [XPMUser/prodidows#15]
### What would you like to add?

It didn't get updates in a while

### Type of suggestion

New Prodidows feature

### I agree to the following

- [x] By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by Prodidows** [comment]
Coming Soon!
