### ISSUE TITLE
ProdidowsOnline won't boot up.

### ISSUE THREAD

**Issue by XPMUser** [XPMUser/prodidows#16]
### What went wrong?

ProdidowsOnline won't boot up.

### How can I reproduce this?

Open this version

### What did the console output?

game.min.js:988  Uncaught SyntaxError: Unexpected identifier 'key' (at game.min.js:988:4)
ProdidowsOnline/?mods=WalkSpeed,FastGameSpeed,ClassicFaces:336  Uncaught ReferenceError: Boot is not defined
    at window.onload (ProdidowsOnline/?mods=WalkSpeed,FastGameSpeed,ClassicFaces:336:13)

**Comment by Toonigy** [comment]
Fix it then
